import {createRouter,createWebHistory} from 'vue-router';
import Home from '@/pages/home/index.vue'
import Hospitals from '@/pages/hospital/index.vue'
export default createRouter({
    history:createWebHistory(),
    routes:[
        {
            path:'/home',
            component:Home
        },
        {
            path:'/hospitals',
            component:Hospitals,
            children:[
                {
                    path:'register',
                    component:()=>import('@/pages/hospital/register/index.vue')
                },
                {
                    path:'detail',
                    component:()=>import('@/pages/hospital/detail/index.vue')
                },
                {
                    path:'notice',
                    component:()=>import('@/pages/hospital/notice/index.vue')
                },
                {
                    path:'close',
                    component:()=>import('@/pages/hospital/close/index.vue')
                },
                {
                    path:'search',
                    component:()=>import('@/pages/hospital/search/index.vue')
                }
            ]
        },
        {
            path:'/',
            redirect:'/home'
        }
    ],
    //滚动条滚动行为
    scrollBehavior(){
        return{
            top:0,
            buttom:0
        }
    }
})